config/routes.rb
Rails.application.routes.draw do
  root 'movies#index'

  resources :users, only: [:new, :create]
  delete 'logout', to: 'sessions#destroy'
  get 'authorized', to: 'sessions#page_requires_login'

  resources :movies
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
  # Association
  belongs_to :user
  # Validation
  validates :url, :title, presence: true
  # Callbacks
  before_save :embed_url

  def embed_url
    if self.url[/youtu\.be\/([^\?]*)/]
      youtube_id = $1
    else
      self.url[/^.*((v\/)|(embed\/)|(watch\?))\??v?=?([^\&\?]*).*/]
      youtube_id = $5
    end

    self.url = "http://www.youtube.com/embed/#{ youtube_id }"
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  # Validation
  validates_uniqueness_of :username
  # Association
  has_many :movies
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  helper_method :logged_in?

  def current_user
    User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def authorized
    flash[:error] = 'Need login or signup'
    redirect_to root_path unless logged_in?
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  # before_action :authorized, only: [:new, :create]

  def index
    @user = User.new unless logged_in?
    @movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = current_user.movies.new(movie_params)

    if @movie.save!
      redirect_to root_path
    else
      render 'new'
    end
  end

  private

  def movie_params
    params.require(:movie).permit(:url, :title, :description)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def destroy
    session[:user_id] = nil
    flash[:notice] = 'logout'
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorized, except: [:new, :create]

  def new
  end

  def create
    if existing_user?
      check_user_login
    else
      sign_up_new_user
    end
    redirect_to root_path
  end

  private

  def existing_user?
    @user = User.find_by(username: params[:user]['username'])
  end

  def user_params
    params.require(:user).permit(:username, :password)
  end

  def check_user_login
    if @user && @user.authenticate(params[:user]['password'])
      session[:user_id] = @user.id
      flash[:notice] = 'login'
    else
      flash[:error] = 'login error'
    end
  end

  def sign_up_new_user
    @user = User.new(user_params)
    if @user.save!
      session[:user_id] = @user.id
      flash[:notice] = 'signup'
    else
      flash[:error] = 'signup error'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShareMovie</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'shared/header' %>
    <%= render partial: 'shared/flash' %>
    <div class="content">
      <%= yield %>
    </div>
  </body>
</html>

app/views/movies/index.html.erb
<% @movies.each do |movie| %>
  <div class="row">
    <div class="column left-frame">
      <iframe width="240" height="120" src=<%= movie.url %>></iframe>
    </div>
    <div class="column">
      <p><%= movie.title %></p>
      <p><%= movie.description.html_safe %></p>
    </div>
  </div>
<% end %>

app/views/movies/new.html.erb
<div class="center">
  <%= form_with scope: :movie, url: movies_path, local: true do |form| %>
    <p>
      <%= form.label :url %><br>
      <%= form.text_field :url %>
    </p>
    <p>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
    </p>
    <p>
      <%= form.label :description %><br>
      <%= form.text_area :description %>
    </p>

    <p>
      <%= form.submit %>
    </p>
  <% end %>
</div>

app/views/movies/show.html.erb
<h1>Movie</h1>
<iframe width="240" height="120" src=<%= @movie.url %>></iframe><br/>
Title: <%= @movie.title %><br/>
Description: <%= @movie.description %><br/>

app/views/shared/_flash.html.erb
<% flash.each do |type, msg| %>
  <div>
    <%= msg %>
  </div>
<% end %>

app/views/shared/_header.html.erb
<div class="header">
  <div class="left-section">
    <%= link_to 'Share Movie', root_path, class: 'heading-title' %>
  </div>
  <div class="right-section">
    <% if @user.present? %>
      <%= form_for @user do |f|%>
        <%= f.text_field :username, placeholder: 'username' %>
        <%= f.password_field :password, placeholder: 'password' %>
        <%= f.submit 'Login / Register' %>
      <%end%>
    <% elsif logged_in? %>
      <span class='username'>Welcome <%= current_user.username %></span>
      <%= link_to 'Share a movie', new_movie_path, class: 'button'  %>
      <%= link_to 'Logout', logout_path, method: :delete, class: 'logout-button' %>
    <% end %>
  </div>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>